<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="zh-cn">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">edef80c4d45512e8019208b11a2d17e9ced24481</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.DuplicateWaitObjectException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">df8b77371dcfbea5fdb07aef51f0a0627d5b859a</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">9fd213f93920569a04e66879a48ee16c8df303e8</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when an object appears more than once in an array of synchronization objects.</source>
          <target state="translated">对象的同步对象数组中多次出现时，将引发异常。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>The common language runtime provides a thread synchronization mechanism based on synchronization objects waiting for execution in an array of &lt;xref:System.Threading.WaitHandle&gt; objects.</source>
          <target state="translated">公共语言运行时提供了基于同步对象的数组中等待执行的线程同步机制&lt;xref:System.Threading.WaitHandle&gt;对象。&lt;/xref:System.Threading.WaitHandle&gt;</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>If the array of &lt;xref:System.Threading.WaitHandle&gt; objects passed to &lt;xref:System.Threading.WaitHandle.WaitAll%2A&gt; or &lt;xref:System.Threading.WaitHandle.WaitAny%2A&gt; contains any duplicate operating system handles, DuplicateWaitObjectException is thrown.</source>
          <target state="translated">如果数组&lt;xref:System.Threading.WaitHandle&gt;对象传递给&lt;xref:System.Threading.WaitHandle.WaitAll%2A&gt;或&lt;xref:System.Threading.WaitHandle.WaitAny%2A&gt;包含任何重复的操作系统句柄，则会引发 DuplicateWaitObjectException。&lt;/xref:System.Threading.WaitHandle.WaitAny%2A&gt; &lt;/xref:System.Threading.WaitHandle.WaitAll%2A&gt; &lt;/xref:System.Threading.WaitHandle&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>For more information, see &lt;xref:System.Threading.WaitHandle&gt;.</source>
          <target state="translated">有关详细信息，请参阅&lt;xref:System.Threading.WaitHandle&gt;。&lt;/xref:System.Threading.WaitHandle&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>DuplicateWaitObjectException uses the HRESULT COR_E_DUPLICATEWAITOBJECT, which has the value 0x80131529.</source>
          <target state="translated">DuplicateWaitObjectException 使用 HRESULT COR_E_DUPLICATEWAITOBJECT，其值 0x80131529。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>For a list of initial property values for an instance of DuplicateWaitObjectException, see the &lt;xref:System.DuplicateWaitObjectException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">DuplicateWaitObjectException 的实例的初始属性值的列表，请参阅&lt;xref:System.DuplicateWaitObjectException.%23ctor%2A&gt;构造函数。&lt;/xref:System.DuplicateWaitObjectException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>&gt; <ph id="ph1">[!NOTE]</ph> &gt;  This exception is not included in the <bpt id="p1">[</bpt>.NET for Windows Store apps<ept id="p1">](http://go.microsoft.com/fwlink/?LinkID=247912)</ept> or the , but it is thrown by some members that are.</source>
          <target state="translated">1&gt; <ph id="ph1">[!NOTE]</ph>&amp;1;&gt; 此异常未包含在<bpt id="p1">[</bpt>.NET for Windows Store 应用<ept id="p1">](http://go.microsoft.com/fwlink/?LinkID=247912)</ept>或的详细信息，但它将引发的某些成员。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>To catch the exception in that case, write a <ph id="ph1">`catch`</ph> statement for &lt;xref:System.ArgumentException&gt; instead.</source>
          <target state="translated">若要在这种情况下捕获异常，编写<ph id="ph1">`catch`</ph>语句&lt;xref:System.ArgumentException&gt;相反。&lt;/xref:System.ArgumentException&gt;</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>类。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error, such as "Duplicate objects in argument."</source>
          <target state="translated">此构造函数初始化&lt;xref:System.Exception.Message%2A&gt;为系统提供的消息描述该错误，如"重复自变量中的对象"。 将新实例的属性&lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>This message takes into account the current system culture.</source>
          <target state="translated">此消息将当前系统区域性考虑在内。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.DuplicateWaitObjectException&gt;.</source>
          <target state="translated">下表显示&lt;xref:System.DuplicateWaitObjectException&gt;.&lt;/xref:System.DuplicateWaitObjectException&gt;实例的初始属性的值</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.ArgumentException.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">|属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|空引用 (<ph id="ph1">`Nothing`</ph>在 Visual Basic 中)。 |  |&lt;xref:System.ArgumentException.Message%2A&gt;|本地化的错误消息字符串。 |&lt;/xref:System.ArgumentException.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the name of the parameter that causes this exception.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>同名会导致此异常的参数的类。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The content of <ph id="ph1">`parameterName`</ph> is intended to be understood by humans.</source>
          <target state="translated">内容<ph id="ph1">`parameterName`</ph>旨在为人所理解。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.DuplicateWaitObjectException&gt;.</source>
          <target state="translated">下表显示&lt;xref:System.DuplicateWaitObjectException&gt;.&lt;/xref:System.DuplicateWaitObjectException&gt;实例的初始属性的值</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.ArgumentException.Message%2A&gt;|The localized error message string.|   |&lt;xref:System.ArgumentException.ParamName%2A&gt;|The parameter name string.|</source>
          <target state="translated">|属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|空引用 (<ph id="ph1">`Nothing`</ph>在 Visual Basic 中)。 |  |&lt;xref:System.ArgumentException.Message%2A&gt;|本地化的错误消息字符串。 |  |&lt;xref:System.ArgumentException.ParamName%2A&gt;|参数名称字符串。 |&lt;/xref:System.ArgumentException.ParamName%2A&gt; &lt;/xref:System.ArgumentException.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>The name of the parameter that caused the exception.</source>
          <target state="translated">导致异常的参数名称。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>用序列化数据的类。</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">在反序列化，以便重建通过流传输的异常对象过程中调用此构造函数。</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>XML 和 SOAP 序列化<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>。</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">承载序列化的对象数据的对象。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">有关源或目标的上下文信息。</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用指定的错误消息和对导致此异常的内部异常的引用的类。</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">前一个异常的直接结果应包含中的前一个异常的引用引发的异常，&lt;xref:System.Exception.InnerException%2A&gt;属性。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed to this constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;属性返回传递给此构造函数的相同值。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.DuplicateWaitObjectException&gt;.</source>
          <target state="translated">下表显示&lt;xref:System.DuplicateWaitObjectException&gt;.&lt;/xref:System.DuplicateWaitObjectException&gt;实例的初始属性的值</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The exception specified by <ph id="ph1">`innerException`</ph>.|   |&lt;xref:System.ArgumentException.Message%2A&gt;|The error message string specified by <ph id="ph2">`message`</ph>.|</source>
          <target state="translated">|属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|指定的异常<ph id="ph1">`innerException`</ph>。 |  |&lt;xref:System.ArgumentException.Message%2A&gt;|指定的错误消息字符串<ph id="ph2">`message`</ph>。 |&lt;/xref:System.ArgumentException.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解释异常原因的错误消息。</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">导致当前异常的异常。</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">如果<ph id="ph1">`innerException`</ph>参数不是<bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>中, 引发当前异常<bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>处理内部异常的块。</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and the name of the parameter that causes this exception.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.DuplicateWaitObjectException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用指定的错误消息和导致此异常的参数的名称的类。</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve">
          <source>The content of the <ph id="ph1">`parameterName`</ph> and <ph id="ph2">`message`</ph> parameters is intended to be understood by humans.</source>
          <target state="translated">内容<ph id="ph1">`parameterName`</ph>和<ph id="ph2">`message`</ph>参数旨在为人所理解。</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve">
          <source>The caller of this constructor is required to ensure that these strings have been localized for the current system culture.</source>
          <target state="translated">此构造函数的调用方需要确保这些字符串已针对当前系统区域性进行了本地化。</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">前一个异常的直接结果应包含中的前一个异常的引用引发的异常，&lt;xref:System.Exception.InnerException%2A&gt;属性。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or a null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic) if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;属性返回相同的值传递到构造函数中，则为空引用 (<ph id="ph1">`Nothing`</ph>在 Visual Basic 中) 如果&lt;xref:System.Exception.InnerException%2A&gt;属性不会提供给构造函数的内部异常值。&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.DuplicateWaitObjectException&gt;.</source>
          <target state="translated">下表显示&lt;xref:System.DuplicateWaitObjectException&gt;.&lt;/xref:System.DuplicateWaitObjectException&gt;实例的初始属性的值</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic)|   |&lt;xref:System.ArgumentException.Message%2A&gt;|The error message string.|   |&lt;xref:System.ArgumentException.ParamName%2A&gt;|The parameter name string.|</source>
          <target state="translated">|属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|空引用 (<ph id="ph1">`Nothing`</ph>在 Visual Basic 中) |  |&lt;xref:System.ArgumentException.Message%2A&gt;|错误消息字符串。 |  |&lt;xref:System.ArgumentException.ParamName%2A&gt;|参数名称字符串。 |&lt;/xref:System.ArgumentException.ParamName%2A&gt; &lt;/xref:System.ArgumentException.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve">
          <source>The name of the parameter that caused the exception.</source>
          <target state="translated">导致异常的参数名称。</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve">
          <source>The message that describes the error.</source>
          <target state="translated">描述错误的消息。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>