<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="pt-br">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">3b57045d08ea0a16088d5cd2fc0ae01f4bee9e74</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Xaml.XamlSchemaException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">b34b2e30a09bcee2aa0796fb648dc7d48ad5768f</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">9dbe9cfd6004d91e84edc43f47fb05050674de5b</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when a binding system or another schema representation system for XAML reports an exception to the schema context.</source>
          <target state="translated">A exceção que é lançada quando um sistema de associação ou outro sistema de representação de esquema para XAML informa uma exceção para o contexto do esquema.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>The XamlSchemaException is thrown by several cases in the CLR binding support classes that provide the schema context for .NET Framework XAML Services (&lt;xref:System.Xaml.XamlXmlReader&gt;, &lt;xref:System.Xaml.XamlObjectWriter&gt;, or &lt;xref:System.Xaml.XamlServices&gt;).</source>
          <target state="translated">O XamlSchemaException é lançada por vários casos em que as classes de suporte de associação de CLR que fornecem o contexto do esquema para serviços XAML do .NET Framework (&lt;xref:System.Xaml.XamlXmlReader&gt;, &lt;xref:System.Xaml.XamlObjectWriter&gt;, ou &lt;xref:System.Xaml.XamlServices&gt;).&lt;/xref:System.Xaml.XamlServices&gt; &lt;/xref:System.Xaml.XamlObjectWriter&gt; &lt;/xref:System.Xaml.XamlXmlReader&gt;</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>A XamlSchemaException is typically passed as the inner exception for other exceptions, such as the &lt;xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName&gt;-true property for a &lt;xref:System.Xaml.XamlObjectWriterException&gt;, so it should be uncommon to catch a XamlSchemaException directly unless you are implementing a component such as a specialized object writer.</source>
          <target state="translated">Um XamlSchemaException geralmente é passado como a exceção interna para outras exceções, como o &lt;xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName&gt;-true propriedade para um &lt;xref:System.Xaml.XamlObjectWriterException&gt;, portanto, ele deve ser comum para capturar um XamlSchemaException diretamente, a menos que você estiver implementando um componente como um gravador de objeto especializado.&lt;/xref:System.Xaml.XamlObjectWriterException&gt; &lt;/xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a system-supplied message that describes the error.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com uma mensagem fornecida pelo sistema que descreve o erro.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified message that describes the error.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com uma mensagem especificada que descreve o erro.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>The message that describes the exception.</source>
          <target state="translated">A mensagem que descreve a exceção.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The caller of this constructor is required to ensure that this string has been localized for the current system culture.</source>
          <target state="translated">O chamador desse construtor é necessário para garantir que essa cadeia de caracteres foi localizada para a cultura atual do sistema.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com os dados serializados.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">O objeto que contém os dados do objeto serializado.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">As informações contextuais sobre a origem ou destino.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.Xaml.XamlSchemaException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com uma mensagem de erro especificada e uma referência à exceção interna que é a causa dessa exceção.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Uma exceção que é lançada como um resultado direto de uma exceção anterior deve incluir uma referência à exceção anterior no &lt;xref:System.Exception.InnerException%2A&gt;propriedade.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">O &lt;xref:System.Exception.InnerException%2A&gt;propriedade retorna o mesmo valor que é passado para o construtor, ou <ph id="ph1">`null`</ph> se o &lt;xref:System.Exception.InnerException%2A&gt;propriedade não fornecer o valor da exceção interna para o construtor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The message that describes the exception.</source>
          <target state="translated">A mensagem que descreve a exceção.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The caller of this constructor is required to ensure that this string has been localized for the current system culture.</source>
          <target state="translated">O chamador desse construtor é necessário para garantir que essa cadeia de caracteres foi localizada para a cultura atual do sistema.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">A exceção que é a causa da exceção atual.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Se o <ph id="ph1">`innerException`</ph> parâmetro não é <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>, a exceção atual é gerada em um <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> bloco que manipula a exceção interna.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>