<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ru-ru">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1029a343e695506629c64a40315e5d9af6b17932</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.IO.IsolatedStorage.IsolatedStorageException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">16e68d9f435d8a9977248b4eb9653007f20c4649</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">cfa388a29467e81ebc82d9e897ba6228d49ca276</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when an operation in isolated storage fails.</source>
          <target state="translated">Исключение, возникающее при сбое операции в изолированном хранилище.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source><ph id="ph1">`IsolatedStorageException`</ph> uses the HRESULT ISS_E_ISOSTORE, which has the value 0x80131450.</source>
          <target state="translated"><ph id="ph1">`IsolatedStorageException`</ph>использует ISS_E_ISOSTORE HRESULT, который имеет значение 0x80131450.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>The most common examples of isolated storage exceptions are as follows.</source>
          <target state="translated">Ниже приведены наиболее распространенные примеры исключений изолированного хранения.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>-   Missing evidence.</source>
          <target state="translated">— Свидетельство отсутствует.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT">
          <source>Isolated storage requires evidence (information about the assembly and its origin) in order to determine the identity of the code and connect it to the correct associated file space.</source>
          <target state="translated">Изолированного хранения необходимо свидетельство (сведения о сборке и ее источнике) чтобы определить удостоверение кода и подключите его к пространство правильное связанного файла.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>Without this information, isolated storage cannot be used.</source>
          <target state="translated">Без этой информации нельзя использовать изолированное хранилище.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT">
          <source>-   Invalid operations.</source>
          <target state="translated">-Недопустимые операции.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT">
          <source>Some &lt;xref:System.IO.FileStream&gt; operations are not supported for isolated storage.</source>
          <target state="translated">Некоторые &lt;xref:System.IO.FileStream&gt;операции не поддерживаются для изолированного хранилища.&lt;/xref:System.IO.FileStream&gt;</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>For a list of initial property values for an instance of <ph id="ph1">`IsolatedStorageException`</ph>, see the &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">Список начальных значений свойств для экземпляра <ph id="ph1">`IsolatedStorageException`</ph>, в разделе &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A&gt;конструкторов.&lt;/xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> класса со свойствами по умолчанию.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.</source>
          <target state="translated">В следующей таблице показаны исходные значения свойств для экземпляра класса &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.&lt;/xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">| Свойство | Значение |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| Строка локализованного сообщения об. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> класса с указанным сообщением об ошибке.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.</source>
          <target state="translated">В следующей таблице показаны исходные значения свойств для экземпляра класса &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.&lt;/xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Свойство | Значение |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| Строка сообщения об ошибке. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Сообщение об ошибке с объяснением причин исключения.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> сериализованными данными.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">Объект, содержащий сериализованные данные объекта.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">Контекстные сведения об источнике или назначении.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.IO.IsolatedStorage.IsolatedStorageException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Исключение, созданное как прямой результат предыдущего исключения, должно содержать ссылку на предыдущее исключение в &lt;xref:System.Exception.InnerException%2A&gt;свойство.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;Свойство возвращает то же значение, которое передается конструктору, или <ph id="ph1">`null`</ph> Если &lt;xref:System.Exception.InnerException%2A&gt;свойства не предоставляет конструктору значение внутреннего исключения.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.</source>
          <target state="translated">В следующей таблице показаны исходные значения свойств для экземпляра класса &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.&lt;/xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Свойство | Значение |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Ссылка на внутреннее исключение. |   | &lt;xref:System.Exception.Message%2A&gt;| Строка сообщения об ошибке. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Сообщение об ошибке с объяснением причин исключения.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">Исключение, которое стало причиной текущего исключения.</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`inner`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Если <ph id="ph1">`inner`</ph> не <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>, текущее исключение сгенерировано в <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> блок, обрабатывающем внутреннее исключение.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>