<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ru-ru">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d487a063dfe1d1b412d495df3baa5bd6c1d11bac</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Windows.Xps.XpsPackagingException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">0c6d276fe113a6b31d36ce8f0f0a9c9290c776f2</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">82a9fdc33f816fce5a265fe8bff29ee2b49d8f73</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when reading, writing to, registering, or accessing in some other way an <bpt id="p1">&lt;xref href="System.Windows.Xps.Packaging.XpsDocument"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>.</source>
          <target state="translated">Исключение возникает при чтении, записи, регистрации или доступ в каком-либо другом, каким образом <bpt id="p1">&lt;xref href="System.Windows.Xps.Packaging.XpsDocument"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> класса.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class that provides a specific error condition.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> класс, предоставляющий определенную ошибку.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; that describes the error condition.</source>
          <target state="translated">Объект &lt;xref:System.String&gt;, описывающий условие ошибки.&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class that provides specific <bpt id="p2">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> and &lt;xref:System.Runtime.Serialization.StreamingContext&gt;.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> класс, который предоставляет определенные <bpt id="p2">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> и &lt;xref:System.Runtime.Serialization.StreamingContext&gt;.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>This constructor is protected.</source>
          <target state="translated">Этот конструктор является защищенным.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The data that is required to serialize or deserialize an object.</source>
          <target state="translated">Данные, необходимые для сериализации или десериализации объекта.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>The context, which includes source and destination, of the serialized stream.</source>
          <target state="translated">Контекст, который включает в себя источник и назначение сериализованного потока.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class that provides a specific error condition and includes the cause of the exception.</source>
          <target state="translated">Инициализирует новый экземпляр <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> класс, который содержит определенную ошибку и причину исключения.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not <ph id="ph2">`null`</ph>, the current exception is thrown in a <ph id="ph3">`catch`</ph> block that handles the inner exception.</source>
          <target state="translated">Если <ph id="ph1">`innerException`</ph> не <ph id="ph2">`null`</ph>, текущее исключение вызывается в <ph id="ph3">`catch`</ph> блок, обрабатывающем внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; that describes the error condition.</source>
          <target state="translated">Объект &lt;xref:System.String&gt;, описывающий условие ошибки.&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>The underlying error that caused the <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>.</source>
          <target state="translated">Ошибка, вызвавшая <bpt id="p1">&lt;xref href="System.Windows.Xps.XpsPackagingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>