<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="sv-se">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">15b9e812b91b1384ebad082865b1fa47cd763912</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Threading.ThreadInterruptedException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">e1f0c553627ecd3db1fd9ec7ce82b641b3a28491</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">5ddb88f7ef5adb88c1457feacf6c323b4b13be1a</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when a <bpt id="p1">&lt;xref href="System.Threading.Thread"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> is interrupted while it is in a waiting state.</source>
          <target state="translated">Undantag som utlöses när en <bpt id="p1">&lt;xref href="System.Threading.Thread"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> avbryts när den är i vänteläge.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>After a thread is created, it is in one or more &lt;xref:System.Threading.ThreadState&gt; states until it is destroyed.</source>
          <target state="translated">När skapas en tråd är det i en eller flera &lt;xref:System.Threading.ThreadState&gt;tillstånd tills den förstörs.&lt;/xref:System.Threading.ThreadState&gt;</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>Calling &lt;xref:System.Threading.Thread.Interrupt%2A&gt; when a thread is in the &lt;xref:System.Threading.ThreadState&gt; state will cause a ThreadInterruptedException to be thrown in the target thread.</source>
          <target state="translated">Anropar &lt;xref:System.Threading.Thread.Interrupt%2A&gt;när en tråd är i den &lt;xref:System.Threading.ThreadState&gt;tillstånd kommer en ThreadInterruptedException positionsundantagsfel i mål-tråden.&lt;/xref:System.Threading.ThreadState&gt; &lt;/xref:System.Threading.Thread.Interrupt%2A&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>If the thread is not in the &lt;xref:System.Threading.ThreadState&gt; state, the exception is not thrown until the thread enters that state.</source>
          <target state="translated">Om tråden inte är i den &lt;xref:System.Threading.ThreadState&gt;tillståndet kan den inte undantag förrän tråden anger det aktuella tillståndet.&lt;/xref:System.Threading.ThreadState&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT">
          <source>If the thread never blocks, it could complete without ever being interrupted.</source>
          <target state="translated">Om tråden blockerar aldrig, kunde slutföras utan att någonsin avbryts.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>ThreadInterruptedException uses the HRESULT COR_E_THREADINTERRUPTED, which has the value 0x80131519.</source>
          <target state="translated">ThreadInterruptedException använder HRESULT COR_E_THREADINTERRUPTED, som har värdet 0x80131519.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT">
          <source>For a list of initial property values for an instance of ThreadInterruptedException, see the &lt;xref:System.Threading.ThreadInterruptedException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">En lista över inledande egenskapsvärden för en instans av ThreadInterruptedException, finns det &lt;xref:System.Threading.ThreadInterruptedException.%23ctor%2A&gt;konstruktorer.&lt;/xref:System.Threading.ThreadInterruptedException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med standardegenskaper.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadInterruptedException&gt;.</source>
          <target state="translated">I följande tabell visas de inledande egenskapsvärdena för en instans av &lt;xref:System.Threading.ThreadInterruptedException&gt;.&lt;/xref:System.Threading.ThreadInterruptedException&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">| Egenskapen | Värdet |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| Den lokaliserade felsträngen meddelande. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med ett angivet meddelande.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadInterruptedException&gt;.</source>
          <target state="translated">I följande tabell visas de inledande egenskapsvärdena för en instans av &lt;xref:System.Threading.ThreadInterruptedException&gt;.&lt;/xref:System.Threading.ThreadInterruptedException&gt;</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Egenskapen | Värdet |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| Meddelandet felsträng. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Felmeddelandet som förklarar orsaken till undantaget.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med serialiserade data.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">Den här konstruktorn anropas under deserialisering till att fylla Undantagsobjektet som överförs via en dataström.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</source>
          <target state="translated">Mer information finns i <bpt id="p1">[</bpt>XML och SOAP-serialiseringen<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>The <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.</source>
          <target state="translated">Den <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> som innehåller det serialiserade objektdata om undantag som genereras.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.</source>
          <target state="translated">Den &lt;xref:System.Runtime.Serialization.StreamingContext&gt;som innehåller detaljerad information om käll- och målservrar.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Threading.ThreadInterruptedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med ett angivet meddelande och en referens till det interna undantaget som är orsaken till det här undantaget.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Ett undantag som utlöses när ett direkt resultat av ett tidigare undantag ska innehålla en referens till det tidigare undantaget i den &lt;xref:System.Exception.InnerException%2A&gt;egenskapen.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">Den &lt;xref:System.Exception.InnerException%2A&gt;-egenskap returnerar samma värde som överförs till konstruktorn eller <ph id="ph1">`null`</ph> om den &lt;xref:System.Exception.InnerException%2A&gt;egenskapen tillhandahåller inte värdet i det interna undantaget för konstruktorn.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadInterruptedException&gt;.</source>
          <target state="translated">I följande tabell visas de inledande egenskapsvärdena för en instans av &lt;xref:System.Threading.ThreadInterruptedException&gt;.&lt;/xref:System.Threading.ThreadInterruptedException&gt;</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Egenskapen | Värdet |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Referens för inre undantag. |   | &lt;xref:System.Exception.Message%2A&gt;| Meddelandet felsträng. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Felmeddelandet som förklarar orsaken till undantaget.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">Undantag som är orsaken till det aktuella undantaget.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Om den <ph id="ph1">`innerException`</ph> parametern är inte <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>, det aktuella undantaget utlöses i en <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> block som hanterar det interna undantaget.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>