<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="nl-nl">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">48397b0b4319e8790777317fd7a8437422b234a8</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.NotFiniteNumberException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">68c68859ce2bc32cb584c3037b2e29d32581c875</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">13bdc11ec948a096507fe3346135c87e87679d46</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when a floating-point value is positive infinity, negative infinity, or Not-a-Number (NaN).</source>
          <target state="translated">De uitzondering die wordt gegenereerd wanneer een drijvende-kommawaarde positieve oneindigheid, negatief oneindig of geen getal (NaN is).</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>NotFiniteNumberException is available for programming languages that do not support the concepts of infinity and Not-a-Number in floating-point operations.</source>
          <target state="translated">NotFiniteNumberException is beschikbaar voor programmeertalen die de concepten van oneindig en geen getal in drijvende-bewerkingen niet ondersteunen.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>NotFiniteNumberException uses the HRESULT COR_E_NOTFINITENUMBER, which has the value 0x80131528.</source>
          <target state="translated">NotFiniteNumberException maakt gebruik van de HRESULT COR_E_NOTFINITENUMBER, dat de waarde 0x80131528 heeft.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>For a list of initial property values for an instance of NotFiniteNumberException, see the &lt;xref:System.NotFiniteNumberException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">Zie voor een lijst met eerste eigenschapswaarden voor een exemplaar van NotFiniteNumberException de &lt;xref:System.NotFiniteNumberException.%23ctor%2A&gt;constructors.&lt;/xref:System.NotFiniteNumberException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">Initialiseert een nieuw exemplaar van de <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error, such as "The number encountered was not a finite quantity."</source>
          <target state="translated">Deze constructor initialiseert de &lt;xref:System.Exception.Message%2A&gt;eigenschap van het nieuwe exemplaar op een systeem geleverd bericht die de fout wordt beschreven, zoals "de aangetroffen aantal is geen eindige hoeveelheid."&lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT">
          <source>This message takes into account the current system culture.</source>
          <target state="translated">Dit bericht wordt rekening gehouden met de huidige systeemcultuur.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">De volgende tabel toont de eerste waarden voor een exemplaar van &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt;</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">| Eigenschap | Waarde |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Een null-verwijzing (<ph id="ph1">`Nothing`</ph> in Visual Basic). |   | &lt;xref:System.Exception.Message%2A&gt;| De gelokaliseerde fouttekenreeks bericht. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the invalid number.</source>
          <target state="translated">Initialiseert een nieuw exemplaar van de <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse met het ongeldige getal.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT">
          <source>The <ph id="ph1">`offendingNumber`</ph> parameter must be both a &lt;xref:System.Double&gt; and an invalid number.</source>
          <target state="translated">De <ph id="ph1">`offendingNumber`</ph> parameter moet zowel een &lt;xref:System.Double&gt;en een ongeldig getal.&lt;/xref:System.Double&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">De volgende tabel toont de eerste waarden voor een exemplaar van &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt;</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;|The invalid number.|</source>
          <target state="translated">| Eigenschap | Waarde |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Een null-verwijzing (<ph id="ph1">`Nothing`</ph> in Visual Basic). |   | &lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;| Ongeldig nummer. |&lt;/xref:System.NotFiniteNumberException.OffendingNumber%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The value of the argument that caused the exception.</source>
          <target state="translated">De waarde van het argument dat de uitzondering heeft veroorzaakt.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">Initialiseert een nieuw exemplaar van de <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse met een opgegeven foutbericht.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT">
          <source>Ensure that the <ph id="ph1">`message`</ph> string is understandable to the user and that it is localized for the current culture.</source>
          <target state="translated">Zorg ervoor dat de <ph id="ph1">`message`</ph> tekenreeks is onbegrijpelijk voor de gebruiker en dat deze is geconfigureerd voor de huidige cultuur.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">De volgende tabel toont de eerste waarden voor een exemplaar van &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt;</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Eigenschap | Waarde |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Een null-verwijzing (<ph id="ph1">`Nothing`</ph> in Visual Basic). |   | &lt;xref:System.Exception.Message%2A&gt;| De fouttekenreeks bericht. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The message that describes the error.</source>
          <target state="translated">Het bericht dat de fout wordt beschreven.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">Initialiseert een nieuw exemplaar van de <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse met de geserialiseerde gegevens.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">Deze constructor is aangeroepen tijdens de deserialisatie op het object exception verzonden via een stroom opnieuw samenstellen.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">Het object dat de gegevens geserialiseerd object bevat.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">De contextuele informatie over de bron- of doelserver.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and the invalid number.</source>
          <target state="translated">Initialiseert een nieuw exemplaar van de <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse met een opgegeven foutbericht en ongeldig nummer.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT">
          <source>Ensure that the <ph id="ph1">`message`</ph> string is understandable to the user and that it is localized for the current culture.</source>
          <target state="translated">Zorg ervoor dat de <ph id="ph1">`message`</ph> tekenreeks is onbegrijpelijk voor de gebruiker en dat deze is geconfigureerd voor de huidige cultuur.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">De volgende tabel toont de eerste waarden voor een exemplaar van &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt;</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;|The invalid number.|</source>
          <target state="translated">| Eigenschap | Waarde |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Een null-verwijzing (<ph id="ph1">`Nothing`</ph> in Visual Basic). |   | &lt;xref:System.Exception.Message%2A&gt;| De fouttekenreeks bericht. |   | &lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;| Ongeldig nummer. |&lt;/xref:System.NotFiniteNumberException.OffendingNumber%2A&gt; &lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve">
          <source>The message that describes the error.</source>
          <target state="translated">Het bericht dat de fout wordt beschreven.</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve">
          <source>The value of the argument that caused the exception.</source>
          <target state="translated">De waarde van het argument dat de uitzondering heeft veroorzaakt.</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is root cause of this exception.</source>
          <target state="translated">Initialiseert een nieuw exemplaar van de <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering die de hoofdoorzaak van deze uitzondering.</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering kan bevatten een verwijzing naar de vorige uitzondering in de &lt;xref:System.Exception.InnerException%2A&gt;eigenschap.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">De &lt;xref:System.Exception.InnerException%2A&gt;eigenschap dezelfde waarde die is doorgegeven aan de constructor of <ph id="ph1">`null`</ph> als de &lt;xref:System.Exception.InnerException%2A&gt;eigenschap levert niet de waarde van de binnenste uitzondering voor de constructor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">De volgende tabel toont de eerste waarden voor een exemplaar van &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt;</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Eigenschap | Waarde |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| De verwijzing naar de interne uitzondering. |   | &lt;xref:System.Exception.Message%2A&gt;| De fouttekenreeks bericht. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Het foutbericht met uitleg over de reden voor de uitzondering.</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">De uitzondering die de oorzaak van de huidige uitzondering.</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not a null reference (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Als de <ph id="ph1">`innerException`</ph> parameter is niet een null-verwijzing (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), de huidige uitzondering is opgetreden tijdens een <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> blok die verantwoordelijk is voor de interne uitzondering.</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message, the invalid number, and a reference to the inner exception that is root cause of this exception.</source>
          <target state="translated">Initialiseert een nieuw exemplaar van de <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse met een opgegeven foutbericht, ongeldig getal en een verwijzing naar de interne uitzondering die de hoofdoorzaak van deze uitzondering.</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering kan bevatten een verwijzing naar de vorige uitzondering in de &lt;xref:System.Exception.InnerException%2A&gt;eigenschap.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">De &lt;xref:System.Exception.InnerException%2A&gt;eigenschap dezelfde waarde die is doorgegeven aan de constructor of <ph id="ph1">`null`</ph> als de &lt;xref:System.Exception.InnerException%2A&gt;eigenschap levert niet de waarde van de binnenste uitzondering voor de constructor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="141" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">De volgende tabel toont de eerste waarden voor een exemplaar van &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt;</target>       </trans-unit>
        <trans-unit id="142" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;|The invalid number.|</source>
          <target state="translated">| Eigenschap | Waarde |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| De verwijzing naar de interne uitzondering. |   | &lt;xref:System.Exception.Message%2A&gt;| De fouttekenreeks bericht. |   | &lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;| Ongeldig nummer. |&lt;/xref:System.NotFiniteNumberException.OffendingNumber%2A&gt; &lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="143" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Het foutbericht met uitleg over de reden voor de uitzondering.</target>       </trans-unit>
        <trans-unit id="144" translate="yes" xml:space="preserve">
          <source>The value of the argument that caused the exception.</source>
          <target state="translated">De waarde van het argument dat de uitzondering heeft veroorzaakt.</target>       </trans-unit>
        <trans-unit id="145" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">De uitzondering die de oorzaak van de huidige uitzondering.</target>       </trans-unit>
        <trans-unit id="146" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not a null reference (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Als de <ph id="ph1">`innerException`</ph> parameter is niet een null-verwijzing (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), de huidige uitzondering is opgetreden tijdens een <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> blok die verantwoordelijk is voor de interne uitzondering.</target>       </trans-unit>
        <trans-unit id="147" translate="yes" xml:space="preserve">
          <source>Sets the <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> object with the invalid number and additional exception information.</source>
          <target state="translated">Stelt de <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> object met het ongeldige aantal en de aanvullende uitzonderingsgegevens.</target>       </trans-unit>
        <trans-unit id="148" translate="yes" xml:space="preserve" extradata="MT">
          <source>&lt;xref:System.TypeLoadException.GetObjectData%2A&gt; sets a &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; with all the exception object data targeted for serialization.</source>
          <target state="translated">&lt;xref:System.TypeLoadException.GetObjectData%2A&gt;Hiermee stelt u een &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;met alle uitzondering objectgegevens die zijn gericht voor serialisatie.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;&lt;/xref:System.TypeLoadException.GetObjectData%2A&gt;</target>       </trans-unit>
        <trans-unit id="149" translate="yes" xml:space="preserve" extradata="MT">
          <source>During deserialization, the exception object is reconstituted from the &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; transmitted over the stream.</source>
          <target state="translated">Tijdens de deserialisatie-de exception-object is aangemaakt de &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;verzonden via de stroom.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;</target>       </trans-unit>
        <trans-unit id="150" translate="yes" xml:space="preserve" extradata="MT">
          <source>For more information, see &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;.</source>
          <target state="translated">Zie voor meer informatie &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;</target>       </trans-unit>
        <trans-unit id="151" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">Het object dat de gegevens geserialiseerd object bevat.</target>       </trans-unit>
        <trans-unit id="152" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">De contextuele informatie over de bron- of doelserver.</target>       </trans-unit>
        <trans-unit id="153" translate="yes" xml:space="preserve">
          <source>The <bpt id="p1">&lt;code&gt;</bpt><ph id="ph1">info</ph><ept id="p1">&lt;/code&gt;</ept> object is <bpt id="p2">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>.</source>
          <target state="translated">The <bpt id="p1">&lt;code&gt;</bpt><ph id="ph1">info</ph><ept id="p1">&lt;/code&gt;</ept> object is <bpt id="p2">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>.</target>       </trans-unit>
        <trans-unit id="154" translate="yes" xml:space="preserve">
          <source>Gets the invalid number that is a positive infinity, a negative infinity, or Not-a-Number (NaN).</source>
          <target state="translated">Hiermee haalt u de ongeldig getal dat een positieve oneindigheid, een negatief oneindig of geen getal (NaN).</target>       </trans-unit>
        <trans-unit id="155" translate="yes" xml:space="preserve" extradata="MT">
          <source>The OffendingNumber property returns the same value as was passed into the constructor, or zero if no value was supplied.</source>
          <target state="translated">De eigenschap OffendingNumber retourneert dezelfde waarde als is doorgegeven aan de constructor, of nul als geen waarde is opgegeven.</target>       </trans-unit>
        <trans-unit id="156" translate="yes" xml:space="preserve" extradata="MT">
          <source>Override the OffendingNumber property to customize the content or format of the invalid value.</source>
          <target state="translated">De eigenschap OffendingNumber voor het aanpassen van de inhoud of de indeling van de ongeldige waarde te vervangen.</target>       </trans-unit>
        <trans-unit id="157" translate="yes" xml:space="preserve" extradata="MT">
          <source>This property is read-only.</source>
          <target state="translated">Deze eigenschap is alleen-lezen.</target>       </trans-unit>
        <trans-unit id="158" translate="yes" xml:space="preserve">
          <source>The invalid number.</source>
          <target state="translated">De ongeldig getal.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>