<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="zh-tw">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">a99f6363a055cbd8272c7514eb695af7843d28b2</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.ContextMarshalException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">4f03db416a94582f880d6aece2e70d42539714fb</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">24008431dee4e83f1d771ae3553ecbbea209b0c8</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when an attempt to marshal an object across a context boundary fails.</source>
          <target state="translated">嘗試跨內容界限封送物件失敗時擲回例外狀況。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>Objects can marshal by value or by reference.</source>
          <target state="translated">傳值方式或傳址物件可以封送處理。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>Any attempt to pass a type that cannot be marshaled through a context boundary will result in a ContextMarshalException.</source>
          <target state="translated">任何嘗試傳遞無法透過內容界限封送處理的類型會導致 ContextMarshalException。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>ContextMarshalException uses the HRESULT COR_E_CONTEXTMARSHAL which has the value 0x80131504L.</source>
          <target state="translated">ContextMarshalException 會使用具有值 0x80131504L HRESULT COR_E_CONTEXTMARSHAL。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>ContextMarshalException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.</source>
          <target state="translated">ContextMarshalException 會使用預設&lt;xref:System.Object.Equals%2A&gt;支援參考相等的實作。&lt;/xref:System.Object.Equals%2A&gt;</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>For a list of initial property values for an instance of ContextMarshalException, see the &lt;xref:System.ContextMarshalException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">如需 ContextMarshalException 的執行個體的初始屬性值的清單，請參閱&lt;xref:System.ContextMarshalException.%23ctor%2A&gt;建構函式。&lt;/xref:System.ContextMarshalException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用預設屬性的類別。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.ContextMarshalException&gt;.</source>
          <target state="translated">下表顯示&lt;xref:System.ContextMarshalException&gt;.&lt;/xref:System.ContextMarshalException&gt;的執行個體的初始屬性值</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The empty string ("").|</source>
          <target state="translated">|屬性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|  |&lt;xref:System.Exception.Message%2A&gt;|空字串 ("")。 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>類別指定的錯誤訊息。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.ContextMarshalException&gt;.</source>
          <target state="translated">下表顯示&lt;xref:System.ContextMarshalException&gt;.&lt;/xref:System.ContextMarshalException&gt;的執行個體的初始屬性值</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">|屬性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|  |&lt;xref:System.Exception.Message%2A&gt;|錯誤訊息字串。 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解釋例外狀況的原因的錯誤訊息。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用序列化資料的類別。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.</source>
          <target state="translated"><bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>其中保存有關擲回例外狀況的序列化的物件資料。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.</source>
          <target state="translated">&lt;xref:System.Runtime.Serialization.StreamingContext&gt;其中包含關於來源或目的端內容資訊。&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.ContextMarshalException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>類別指定的錯誤訊息以及造成此例外狀況的內部例外狀況的參考。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">做為前一個例外狀況直接結果應該包括在前一個例外狀況的參考就會擲回的例外狀況&lt;xref:System.Exception.InnerException%2A&gt;屬性。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;屬性會傳回相同的值傳遞到建構函式，或<ph id="ph1">`null`</ph>如果&lt;xref:System.Exception.InnerException%2A&gt;屬性沒有提供內部例外值給建構函式。&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.ContextMarshalException&gt;.</source>
          <target state="translated">下表顯示&lt;xref:System.ContextMarshalException&gt;.&lt;/xref:System.ContextMarshalException&gt;的執行個體的初始屬性值</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">|屬性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|內部例外狀況參考。 |  |&lt;xref:System.Exception.Message%2A&gt;|錯誤訊息字串。 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解釋例外狀況的原因的錯誤訊息。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">造成目前例外狀況的例外狀況。</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`inner`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">如果<ph id="ph1">`inner`</ph>參數不是<bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>中, 引發目前的例外狀況<bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>處理內部例外狀況區塊。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>