<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="zh-tw">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">257fda0e7c6b22b25ba87f68e5e86cd657c350d2</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Runtime.Remoting.ServerException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">a45ac4e10b0f593441eef19f784387c74a7ad1f2</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">40c2bfde8b93a379b57be1b992d1aa80188b7eec</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown to communicate errors to the client when the client connects to non-.NET Framework applications that cannot throw exceptions.</source>
          <target state="translated">當用戶端連接至無法擲回例外狀況的非.NET Framework 應用程式時，用戶端通訊錯誤擲回的例外狀況。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>ServerException uses the HRESULT COR_E_SERVER, which has the value 0x8013150E.</source>
          <target state="translated">ServerException 會使用 HRESULT COR_E_SERVER，0x8013150E 的值。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>ServerException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.</source>
          <target state="translated">ServerException 會使用預設&lt;xref:System.Object.Equals%2A&gt;支援參考相等的實作。&lt;/xref:System.Object.Equals%2A&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>For a list of initial property values for an instance of ServerException, see the ServerException constructors.</source>
          <target state="translated">如需 ServerException 的執行個體的初始屬性值的清單，請參閱 ServerException 建構函式。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用預設屬性的類別。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.ServerException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.ServerException&gt;繼承自&lt;xref:System.SystemException&gt;類別。&lt;/xref:System.SystemException&gt;&lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The empty string ("")|</source>
          <target state="translated">下表顯示&lt;xref:System.Runtime.Remoting.ServerException&gt;類別的執行個體的初始屬性值: |屬性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|空字串 ("") |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified message.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>類別具有指定的訊息。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.ServerException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.ServerException&gt;繼承自&lt;xref:System.SystemException&gt;類別。&lt;/xref:System.SystemException&gt;&lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property Type|Condition|   |-------------------|---------------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The <ph id="ph2">`message`</ph> string|</source>
          <target state="translated">下表顯示&lt;xref:System.Runtime.Remoting.ServerException&gt;類別的執行個體的初始屬性值: |屬性類型 |條件 |  |-------------------|---------------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|<ph id="ph2">`message`</ph>字串 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The message that describes the exception</source>
          <target state="translated">描述例外狀況的訊息</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>類別指定的錯誤訊息以及造成此例外狀況的內部例外狀況的參考。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">做為前一個例外狀況直接結果應該包括在前一個例外狀況的參考就會擲回的例外狀況&lt;xref:System.Exception.InnerException%2A&gt;屬性。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;屬性會傳回相同的值傳遞到建構函式，或<ph id="ph1">`null`</ph>如果&lt;xref:System.Exception.InnerException%2A&gt;屬性沒有提供內部例外值給建構函式。&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string|</source>
          <target state="translated">下表顯示&lt;xref:System.Runtime.Remoting.ServerException&gt;類別的執行個體的初始屬性值: |屬性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|內部例外狀況參考 |  |&lt;xref:System.Exception.Message%2A&gt;|錯誤訊息字串 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解釋例外狀況原因的錯誤訊息。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">造成目前例外狀況的例外狀況。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`InnerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">如果<ph id="ph1">`InnerException`</ph>參數不是<bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>中, 引發目前的例外狀況<bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>處理內部例外狀況區塊。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>